### ISSUE TITLE
Volume Sliders misplaced

### ISSUE THREAD

**Issue by DooMGuy87** [aa2g/AA2Unlimited#11]
Given the fact that the game wasn't supossed to have too much custom personalities, some of the personality volume sliders doesn't appear, appear misplaced or appear above an existent personality slider (look at AA1 Handsome slider over Carefree) when you have lots of custom personalities installed.
Here is an image that shows how they appear in the second page of the personality volume settings.
![](http://i.imgur.com/H3bhW5P.jpg)
Now, would be possible to move them in a new page or rearrange them better in the same page?

**Comment by linkanon** [comment]
This seems to be out of scope of AAUnlimited's features, would require some considerable work since there's currently no way to add more pages to the Settings and is a minor inconvenience in my opinion. Maybe it will be fixed when/if we start adding stuff to the settings menu. I personally wouldn't count on that though.
