### ISSUE TITLE
crashes during interactions

### ISSUE THREAD

**Issue by jackattackman1** [aa2g/AA2Unlimited#146]
![screenshot 1](https://user-images.githubusercontent.com/49208129/55428032-3a12db80-5580-11e9-9995-ce5fd5319762.jpg)

**Comment by Mirgosoft** [comment]
I have same it with wrong (corrupted) launcher.

**Comment by kayfour** [comment]
Unfortunately we can't help you. Your report is not informative. Please refer to [this page ](https://github.com/aa2g/AA2Unlimited/wiki/How-To-Report-a-Crash) to find out how to give us a better crash report.

**Comment by OrdinaryMagician** [comment]
I went in and reproduced this (since I'm seeing the crash quite often). Here's everything attached, I just hope it's valid since I'm running on Wine. All I had to do was start a school day and talk a couple times with the first character I came across.

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/3179052/aaucrash.zip)

**Comment by Scout25DA** [comment]
Try to reinstall AA2 game make sure you've downloaded it right.

**Comment by LunarShadow55** [comment]
[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/3375011/aaucrash.zip)
Not entirely sure if doing it right but having the same problem. it appears to be a module that is affecting it. Originally thought it was the Bully module but attempt number 3 denies that it is. I did already reinstall and made a new class and characters for it but it could be either the module or dialogue from the module considering it only starts when they talk to you and not you to them. will add more if i find out what module starts the crash.

**Comment by linkanon** [comment]
to eliminate the influence of modules disable them in the launcher window and try again. If the problem stops happening then it is indeed the modules and you'd have to find out which one by removing them one by one until it works. Don't forget to update the modules and AAU to the latest versions, of course.

**Comment by LunarShadow55** [comment]
Updated to latest version and not sure if the Update Modules button does that as nothing changes but since i only recently downloaded AAU so i should have the most recent versions of everything. While playing without Modules, the one time i crashed was this time in an attempt to interact with someone. it is someone i hadn't interacted with in that attempt.
[aaucrash4.zip](https://github.com/aa2g/AA2Unlimited/files/3375075/aaucrash4.zip)
I used the quick and easy download from https://tsukiyo.me/AAA/AA2Mini.xml as i don't have the AA2 i used before on this computer and it might be a few years behind but i will use a normal torrent download if necessary

**Comment by linkanon** [comment]
For updating modules refer to [the wiki page](https://github.com/aa2g/AA2Unlimited/wiki/Modules#how-do-i-update-modules)
The game has a case of some random crashes, usually due to the win10fix/wined3d implementations. Make sure your crash is consistent and whether it was/wasn't caused by modules

**Comment by LunarShadow55** [comment]
it was originally consistent but crash number 4 is the first difference in how it happened. Thanks to you letting me know how to turn of modules, i was able to confirm that the game crash is outside of the modules. i might try to download the newest versions of everything again, this time separately to make sure everything is both up to date and that i have a working AA2 before getting AAU online. It could be that the win10fix/wined3d is doing something as well so if you have an idea on how to fix it, i would like to attempt that before restarting again. I would also like to know if the modules zip is meant to remain zipped or if i am meant to extract them into the module file

**Comment by linkanon** [comment]
If you're on a more recent nvidia card you can try the new option in win10fix script settings: `dgvoodoo`
Modules should be extracted in `data/override/modules`
More info in the wiki, I suggest you do some reading.

**Comment by LunarShadow55** [comment]
win10fix and wined3d conflicting. do i turn of wined3d if i wish to turn on win10fix?

**Comment by LunarShadow55** [comment]
the switch to win10fix-dgvoodoo appears to have been the necessary fix, thank you for your help

**Comment by OrdinaryMagician** [comment]
I wanna report that the crashes on my end went away completely after updating.

**Comment by iadda01** [comment]
I found applied just again your repatch.bat it works 200% for me. I had the error when I started the game
