### ISSUE TITLE
Error When Opening AA2 JSF with AA2Unlimited

### ISSUE THREAD

**Issue by SlinkieChan** [aa2g/AA2Unlimited#192]
![Annotation 2019-12-17 160056](https://user-images.githubusercontent.com/46083649/71034125-afaae180-20e6-11ea-8bb5-42778b42ceb4.png)
![Annotation 2019-12-17 160055](https://user-images.githubusercontent.com/46083649/71034138-b9344980-20e6-11ea-9cab-6ac1e7ad86dd.png)

**Comment by mrlurker1994** [comment]
¿Haven't you tried starting AA2play instead of AA2play JSF?

**Comment by tsuyoshikurochi** [comment]
This happend to me, i tried opening the game with AA2PLAY and AA2JSF and neither worked, Edit doesnt work either. Same error.

**Comment by Gauax** [comment]
I'm not sure if It's also gonna work for you but I kept having that error, what I did is Un-check Type 2 Renderer from Graphic tab in AA2Unlimited Menu and then Disabled "win10fix" and Enabled "wined3d" and my game was running but only on AA2Play not AA2PlayJSF, I tried something randomly and it worked for me, go to your AAUnlimited folder (the one that contain the install.bat and etc) and search for "wined3d.dll" when you found it simply copy it and paste it into your AA2Main and AA2Edit folders but rename it to d3d9.dll and run your JSF Launcher or whatever you are using, this method worked for me, I don't know if it causes other issues but since my game runs smoothly and doesn't give errors I'm fine with it (FOR NOW)

**Comment by Gauax** [comment]
> This happend to me, i tried opening the game with AA2PLAY and AA2JSF and neither worked, Edit doesnt work either. Same error.

You may want to try the solution I wrote, It may work for you but no promises, It worked for me!

**Comment by tsuyoshikurochi** [comment]
> > This happend to me, i tried opening the game with AA2PLAY and AA2JSF and neither worked, Edit doesnt work either. Same error.
> 
> You may want to try the solution I wrote, It may work for you but no promises, It worked for me!

Thanks a lot, It helped me, Now aa2 And aa2edit Works! It was the thing of copying the data.
