### ISSUE TITLE
Dumped sound files are completely unreadable

### ISSUE THREAD

**Issue by OrdinaryMagician** [aa2g/AA2Unlimited#203]
I wanted to get some voice lines from the game, so I dumped them from console. Noticed that the files get renamed to have a .wav.opus extension, which is weird... still, they have no recognizable format. Is this some sort of weird headerless hacky thing or am I doing something wrong?

**Comment by linkanon** [comment]
The dev is MIA and he took his secrets to his grave. If you just want to get the voice files you can get them from the original mods or from the vanilla game.
[Here](https://mega.nz/#F!sYV12L5b!1AF4II7y47GsK_nGQ3UDRg) is the full vanilla game backup, voice files are in jg2p05...pp archives
[Here](https://mega.nz/#F!jt8C2bhb!gxmBLpGko-oLtcOte8jlqA) is the HEXAPP that has a lot of moded personalities, most of which are ports from AA1

Let me know if you got these so that I can take down this questionably legal post

**Comment by OrdinaryMagician** [comment]
Got just what I needed, thank you.
