### ISSUE TITLE
Integer slot data type

### ISSUE THREAD

**Issue by geneishouko** [aa2g/AA2Unlimited#22]
AAUnlimited could duplicate slot data the regular card normally holds but use 4 bytes for storage. For example, this would allow for 4 billion hair slots. Practically unlimited slots. This could be accomplished by writing slot number data in the AAUnlimited area. During card load that data would be read instead of the card data, if it exists.

**Comment by AA2Hackanon** [comment]
Unfortunately it won't be that easy. If you take a look at the CharacterData, which is the games/makers representation of a card, it uses bytes in there as well, so simply reading a dword instead is not possible. As a Result of that, aa2s code uses bytes in many places where it handles slots as well, so simply looking at all places that read the slots and changing those will not suffice either. Patching every single instruction would be incredibly much work, especially instructions that use immediates, as they would grow in size and therefor require a jump to a location with new code. And all that is assuming that there are no semantics that assume a slot limit of 255, such as buffers of static sizes holding information. The 6 tans, for example, seem to have some sort of assumption, and my attempt to increse the limit caused crashes i could not track down.

Meanwhile, overriding archives the same goal without any of these problems. If your problem is that you can not scroll through overrides like you can through, for example, hair slots, consider if a specialized override like they exist for tans and eye highlights is enough for that.
