### ISSUE TITLE
Poser Dialog Mockup

### ISSUE THREAD

**Issue by geneishouko** [aa2g/AA2Unlimited#23]
I made a [mockup](/geneishouko/AA2Unlimited/tree/poser_mockup) of what could be put into the poser dialog. Some features are taken and proven from SpoilerAL, while others were made up in the spot.

![poser](https://cloud.githubusercontent.com/assets/19700410/21205000/0304b9d0-c228-11e6-9660-ec9998ac4299.png)

**Comment by AA2Hackanon** [comment]
- noticeably missing are the rotation sliders for different bones/frames. 
- i'm not sure if i will be able to find the dimmed eyes/tears stuff. but i guess we'll see
- i don't think a freeze checkbox will be necessary; its kinda hard to implement, but its easy to archive the same effect with just pose and frame selection 
- also, what is a pose list?

apart from that, looks like a plan. specifically the rotation sliders really need a place though. or a new interface in general.

**Comment by geneishouko** [comment]
![image](https://cloud.githubusercontent.com/assets/19700410/21532471/79aef55e-cd1e-11e6-8f4d-9369a30155e4.png)
Something I'm working on.

**Comment by geneishouko** [comment]
![image](https://cloud.githubusercontent.com/assets/19700410/21546242/6e57b9e2-cdab-11e6-841d-f91033753de0.png)
Slider mods, loading and saving working. Yay.

**Comment by linkanon** [comment]
Good job.
For usability I suggest making several tabs for the bones like L/H hand, head/neck, legs and so on. Alternatively there could be a drop-down with all these categories and selecting it will populate the bones list. As it is in test8 scrolling through all the bones is a major pain

**Comment by geneishouko** [comment]
![image](https://cloud.githubusercontent.com/assets/19700410/21554042/57d0f7ea-cdda-11e6-8d02-c702c6645116.png)
I want to keep the UI compact so I attempted to make one without too much cluttering (but mostly because tab handling in win32 is something that I still don't get).

The bones are abit unmanageable like this. I'm thinking of making a two-tab list for L/R bones. Picking the left or right tab will show and select bones of each side. Central/non-lateral bones would show on both tabs.

**Comment by linkanon** [comment]
instead of two lists with mostly the same bones you could adapt the same idea with tabs to two lists.
It'll look like:
|`Body part`||`Bone`||`Operation`||`Axis`|
`Body part` will list items like `neck`, `left arm`, `left hand`, `right arm`, `right hand`,  etc.
`Bone` will list items like `shoulder`, `arm`, `elbow`, `forearm`, all the finger bones, etc.
`Operation` and `Axis` are fine

Selecting an item in `Body part` would refresh the `Bone` list. This implementation is actually better than with tabs imo. Not sure how to go about the bone lists and their categories. Probably best to list them in poserframes.txt

**Comment by geneishouko** [comment]
I'm liking that. It makes good use of vertical and horizontal space. Let's see if we're seeing it the same way:

Each of 
_|Body part||Bone||Operation||Axis|_
would be list boxes filled with different categories

For the poserframes.txt file I'm thinking of the following structure:

```
_desc_ Friendly Frame Description
_ bone_category bone_name allowed_operations allowed_axis _
```

where _desc_ is optional. if omitted the bone name is used instead. _ bone_category _ groups bones and allowed_operations and _allowed_axis are a list of keywords that restrict bone modifications.

**Comment by linkanon** [comment]
Yes, `Bone` list would have a subset of the list we have right now, `Body part` would have some more general categories(i.e. body parts) each set of bones belongs to.
For keywords I suggest something simple like `SRT`, `SR for operations`, `XYZ`, `XZ` for axes (Though I doubt limiting axes would ever come in handy)
Don't like having desc on  a separate line. Ideally would be to keep a single line per entry. Maybe move it to the end of the entry like 
```
bone_category bone_name allowed_operations allowed_axis desc
```
This way the optional field is the last one so there's no need for empty columns in front of the entry. Only Issue I see with this is that the names won't be nicely lined up because of the frame names. Also i like calling it name in this case since it's not a full-blown description but a simple 1-3 word human-readable alias.

**Comment by linkanon** [comment]
Made a mock-up of hypothetical props controls. The idea is to be able to load an arbitrary .xx and control its SRT.

![image](https://cloud.githubusercontent.com/assets/13915973/22063906/e7d74ea2-dd89-11e6-82f7-0c28760668fc.png)

**Comment by geneishouko** [comment]
I'd keep the bones/frames list for props as well. You may make custom a custom poserframes.txt file for them too.

Also, it seems you are thinking of saving scenes as opposed to just a single pose. I thought of that too but that would need of more UI work. Maybe we could add "Save pose" & "load pose"  buttons below the Categories list for single pose saving/restoring, a reset pose button as well in the row below. Then the Save, Load and Reset buttons at the bottom would work for scenes.

The Props UI needs a bit more spacing away from the Facial UI. I suggest to place the top (the static labels) at (Blush edit)(top) + (Blush edit)(height) + 12 and move everything else accordingly.

**Comment by linkanon** [comment]
Having the same list would work now that I think about it. We can have a `Props` category (instead of the `Rooms` we currently have. Rooms can be treated as props) which will contain all the props we load(we can't list them in `poserframes.txt` because we select them during runtime)

I'm not thinking of saving the whole scene but I suggest attaching the props to the pose as well. One example could be to add a cigarette prop to the smoking pose. If there's no cigarette model the character would just smoke air cigars. Another example is the vanilla `evaluating condom` pose.

If we make props a subset of posing(the `Props` category) we can keep the same exact UI we currently have(maybe with the additional `Add ...`/`Remove` buttons for props). Save/Load would simply save/load the prop filepaths(can be relative to the `overrides`) and their SRTs as well.

A bit offtopic but all the unimplemented features controls should be disabled until implemented to pre-empt the questions in the thread. `Reset`, `Pick from pose list` and `Freeze` don't work now.

**Comment by geneishouko** [comment]
I tried to figure out a way to get the mouse cursor to appear when Always on top is checked without success.
https://github.com/geneishouko/AA2Unlimited/compare/always_on_top...geneishouko:mouse_events
