### ISSUE TITLE
More High Poly Scenes Events

### ISSUE THREAD

**Issue by geneishouko** [aa2g/AA2Unlimited#25]
To enable proper user of the poser outside the clothes editor it would be great to have _start_ and _end_ events for conversations, interruptions and sex scenes that allow one to prepare the poser for the characters that are about to load.

**Comment by AA2Hackanon** [comment]
I assume you mean events that trigger before the h scene / conversation loads. I can see if i can find something, though i wouldn't get my hopes too high, sounds like a lot that can go wrong (conversation/hmode struct doesnt exist at all this early, so no information would be available, i'd probably need to find a different place for every single way to initiate a conversation/hmode, and i didn't even find out what types of conversations actually exist to begin with).

Until then, consider if the ticks aren't enough for what you want to do. The h-ticks allready offer a way to determine the start and end of an h scene, and while the conversation struct doesnt, its probably much easier to find than start/end events.

(Also, i guess interruptions are just conversations. You even found their ids it seems.)

**Comment by geneishouko** [comment]
I'm not looking for any structs. I 'm just thinking of calling StartEvent before the models load just like in the clothes scene. I see I can use the H mode ticks for my purposes and the conversation ticks do half the job. The only thing I'm missing is to detect the end of a conversation.

**Comment by geneishouko** [comment]
Right now the dialogue poser stays in a dangerous unclean state and crashes on a new save load. It is HIGHLY experimental as of now.
 May there any workaround you can see to do a cleanup before loading a save?

**Comment by linkanon** [comment]
+1
this crash is also present of you try to load during POV. It's not as pressing there though because people don't usually load during H but still it could be fixed.

**Comment by AA2Hackanon** [comment]
added 2 events for event start/end respectively. Try using them to disable the poser after a conversation ends. (should fix the load crash automatically i guess)

Also, if you could move add the face xx file information that you have to the external classes (with a few comments if possible) for future use, that would be cool

**Comment by geneishouko** [comment]
No more poser crashes here. Thank you. I stopped myself from adding to XXFile as that's a very core class to AAU. If you find it good to add such face specific values to it, I'll do it. In other news, I found the Frame flags and its submeshes flags. I can make objects disappear with them but unfortunately it seems that is not the mechanism used to disappear tears.

**Comment by AA2Hackanon** [comment]
you can make a seperate class (something like XXFaceFile) and write into the comments that that is an XX file and can be casted.

As for the tears, are you sure the mesh is loaded in the first place? I remember trying to switch the strapon-mesh on in aaedit, but it looked like the mesh somehow wasnt even loaded to begin with. Once its loaded, there cant be too many ways to hide it.

**Comment by geneishouko** [comment]
I don't know about the mesh itself, but the number of frames in memory with the mesh name didn't change between the appearances and disappearances of the tears. I did the search by looking for the frame name, with and without tears. I always got the same 2 Frame-like objects and 2 other things. (except at the beginning of the scene where I got an additional string result that never appeared again.

**Comment by AA2Hackanon** [comment]
took a look at the tear stuff and found a flag that looks like it can be used to hide/show frames. Added it to the aaedit cheat table only, so if you want to try it in aaplay, you'll have to add it to that tables struct first. Also added it to the frame.h (though im not really sure what exactly it does and why the game sets it to 2 to hide).

![pic](https://cloud.githubusercontent.com/assets/16391264/21947177/16d49632-d9e4-11e6-94e7-e74c2f94817d.jpg)

As a general tip, try looking in the editor instead of the game if you want to find something. They share the same structs, but the editor is much easier to manipulate since you have more control over what is happening.

**Comment by geneishouko** [comment]
Thanks for the tip.

As for the hidden flag. Do you know what the game does with that value? Does it compare to a constant or does it use it to substract from somewhere else? If the latter, it could be related to submeshes flags which usually their first byte is 02. Now that I check, the only value that makes a difference is 2. The others are the same so I doubt the submeshes flags have anything to do with it.

I added the XXFileFace class. I named it that because I want to emphasize it's an XXFile overall. I didn't really find those values, I just got them from the SpoilerAL game hack. But I did take a look at them and found those pointers lead to a series of frames/meshes and finally to the blush materials.

**Comment by AA2Hackanon** [comment]
the weird flag is directly compared to 2. there is a flag value at 20A that is combined out of 208 and 209 (constantly, several times a second). if 208 is set (or 20A of the parent frame has its first bit set), 20A |= 1, and if 209 is exactly 2, 20A |= 2.
later 20A is looking at the second bit (20A | 2) to determine if some matrix functions should be skipped.

On that note, the first bit (208) seems to disable the refreshing of matrix2 if enabled (and with that any animations or placement changes), but oddly enough that is done by directly looking at 208 instead of the combined flag value 20A, which only ever seems to be checked for the 2 flag (unlike 209, which seems to be used exclusively to build 20A).

Under normal circumstances i would say i have some horrible misunderstanding of the program here, but i would be inclined to scrap this off as glorious nip coding.

**Comment by geneishouko** [comment]
Thanks for the insight on the use of the variable.

By the way, this flag does not only hide the mesh of the named frame, it also hides everything deeper in the frame subtree.  It might be useful for hiding faces.
