### ISSUE TITLE
Create AA2Unlimited Play Main Window

### ISSUE THREAD

**Issue by geneishouko** [aa2g/AA2Unlimited#31]
In the interest of adding more functionality to AAUnlimited's side of the game there could be a main AAUnlimited window for AA2Play that lets us enable and disable any feature during runtime. Even better, it would let us implement a live class editor for the current loaded save. My initial plan is to enable and disable the poser at will during gameplay.

My idea is:
* Create a window on game start or class load.
* Add class load notification events

**Comment by AA2Hackanon** [comment]
In my personal experience, i keep the poser activated and ignore it during gameplay. It pops up behind the aa2 window once i put it behind there, so it doesnt really get in the way. Im not sure if adding a window just for that feature would justify the work.
If AAU is supposed to get trainer-like abilities at some point a separate window might make sense, though there already is a aa2 trainer out there, so consider if running that one might not be a better alternative to that.
You are of course free to implement it; the class load events and class structs are there already. I personally don't see much use for it yet, though.

**Comment by linkanon** [comment]
As of the most recent build the poser pops up every time so you can't ignore it like before. Probably a side effect of the `always on top` implementation. That behavior where it only pops up the first time would be useful for the common AAU window.
The window is not just for the poser but for future features. Say, for example, being able to monitor the student activity like in AA2Trainer would go into the same window in a different tab/category. Also being able to edit the effective config mid-play would be helpful. I can think of dozens of potential features that could be implemented and would benefit from the consolidated UI.
While AA2T gives access to some neat features I, personally, have a lot of design problems with it so implementing them on the side of AAU is much more preferable. It has some bugs like girls spontaneously lowering their virtue, crashes, the UI is horrid and breaks on some systems(mine, for instance, where half of the roster is cut off and tabs take half of the screen). Its developer is effectively dead so it's gonna stay in this broken state.

On an unrelated note: I've created a task tracker on _teamclerk.com_ where we can add, assign and plan bugs and features.
![image](https://cloud.githubusercontent.com/assets/13915973/22707953/28a3467c-ed7d-11e6-83c4-d51405642de3.png)
 I'd like to add you to the team but I need your email(even a throwaway one will do). There's also a few things only you have the expertise to do, like adding some additional events, and fixing the extra hairs. There's one bug (that I wanted to fix) that is stuck because there's no proper event for it(model unloading, specifically, or general low poly movement, or menu screen).
Me and @geneishouko never know if you're still working on AAU. It's fine if you don't (I've been mostly just managing it lately myself) but it would be nice to ask for some specific advice from time to time. We coordinate primarily through the [/aa2g/ steam group](http://steamcommunity.com/groups/AdeptusHomosexualus) because of the real-time conversations and because the thread itself is useless for feedback. If you're concerned about joining it then it's not necessary if all you need from it is the chat there's plenty of guests in there that come once in a blue moon.

Sorry for the wall of text but you've been absent for a while.

**Comment by AA2Hackanon** [comment]
If you find good use for the window, go for it. If its a general window, it might be reasonable to open it when aau initializes; would have the added benefit of being an indicator that the injection was successful. The class load event also exists already (its called SaveLoadEvent, which is a kinda unfortunate name now that i look at it). However, keep in mind that re-implementing the aa2 trainer would not only be a lot of work but also requires a lot more knowledge about the game, specifically about interactions and relationships.

I'm not sure what you would need a model unloading event for, but keep in mind that you can check if a character is currently loaded by comparing his body xx file to null. Coincidentally i was planning to go on event hunt next anyway (for the trigger system), so if you really need it, i'll add it.

MailForGamesAndSuch@gmail.com is the email i use for this github account (and for testing out games that require registration), if a "throw away" email really suffices. (i wont look into it)
I don't know if i'm still working on AAU myself most of the time. I'm not a really decisive person and quickly get bored, so i sometimes just stop working for a week or two and then come back. And sometimes i don't come back at all, like after aaface. I also don't have steam installed, im not using skype or discord and am generally hard to reach. I like not having to communicate when i don't feel like doing it. I'm sorry i'm autistic like that. If the poser is anything to go off of, you're doing a fabulous work without me though, so i don't think my advise is necessary.

As for the event stuff, i abandoned the standards i had about that relatively quickly. If it works, its good enough. I added my cheat tables to the git at some point, so you don't have to start from scratch if you try to find some yourself (though you will have to use cheat engine then). It's a little chaotic (bones are frames and childless bones are bones, for example) but i hope you get by. 
If you are asking how to find the places in the aa2 code that might be interesting (the debugger work itself), I'm afraid there is not really a guide you can follow to archive that. At the end of the day, you're trying to find places in a code you don't even know that is so big that you can't reasonably read large chunks of it, let alone the whole program. You put a breakpoint at something that you suspect is close to the place you are looking for (typically a function you have found earlier, a winapi / c library call that you know they must be calling (e.g if you try to find where he plays karaoke songs, putting a breakpoint in CreateFile might seem reasonable) or a variable you found earlier that you put a read/write breakpoint on) and try to step and breakpoint yourself through the assembler code from there until you reach the point you were looking for. More guesswork than anything.

**Comment by geneishouko** [comment]
The idea for disabling the poser was just a starting point. With a main play window we could also implement dynamic shadow sets activation and inactivation, which I had in mind right when I thought of sets but I compromised for filename activation because I don't know assembly hackery.

Regarding the existing trainer, I havent tested it as it requires lowering the security setting of Windows UAC, which I'm not keen on doing. (but I might force myself to as I should research what already exists there. the feature set is impressive).

Regarding the poser, do you have any thoughts on how to do certain things in it? Like we want to add items and the method we have for it right now is rather cumbersome: adding meshes to the skeleton XXs. I have to ideas to improve that:

1. Poser specific overrides, which would load alternative skeletons only when the poser is enabled.

2. Additional room files loading: Like with extra hairs, I wonder if it's possible to load more than one .xx file when the room changes.

And about room changes, is it possible to force loading a particular .xx file? It would improve the ease of room modding for H-scene posing.

There are many things that could be done with AAU with the proper event support and maybe even scripting. Think random clothes and hair styles changer. These already exist in japanese tools but have some rather cryptic configuration files.

**Comment by AA2Hackanon** [comment]
if you mean reducing the UAC to get rid of the save desktop because of the lack of lost device handling in aa2, you can just start the trainer at the first window (similar to aau) to circumvent that.

loading additional xx files is not the easiest thing to do. i tried to do that with the additional hairs at first and it resulted in lots of crashing. we would need a throughout understanding of how aa2 allocates, renders and deletes xx files to do that, which might be pretty hard to do. I worked around it by repeatedly calling the function that sets a characters hair and saving the xx file pointers between those calls, but it looks like this has multiple issues as well (i remember people on aa2g saying they look differently and pop in place at the beginning of a scene). I'm not sure what happens to associated files (e.g .xa files) as well.
So, until we know all of that for sure, adding meshes might be the best idea for now.

if the room xx files follow a naming pattern that can be detected, you could write something similar to an archive file override for it that can be controlled over the poser window. Else, one would need a room load event, but that shouldnt be too hard to find.

hair style changes sound like something that could belong to the trigger system. would need a way to define multiple hair styles in an aau card first though. random clothes, on the other hand, sounds horrible. youre not putting randomized cards into your class either.

**Comment by geneishouko** [comment]
>would need a way to define multiple hair styles in an aau card first though
that would be nice to have. the existing implementation sets hairs styles in a configuration file that is capable of using conditionals such as personality, name, seat position, etc.

random clothes is similar. it's not entirely random and works in a similar style to the hair randomizer, by defining a set of clothes styles limited regarding the selection of settings and assigning them, again, with a set of conditionals to each npc.

That's a good and simple idea for the room changer. so far we have been disciplined and the 3d rooms mod follows the same naming pattern the game uses, so it could work. The idea would be to add another case in ArchiveFileOpen.cpp, right? The only downside is if someone adds a room with a name breaking the pattern it falls apart.

**Comment by linkanon** [comment]
We've got a couple people who are confident in their knowledge of the game's mechanic so re-implementing AA2T, at least partially, is completely possible.

`SaveLoadEvent` is useful for cleaning up the data from the `Facecam` module so I'll try using that instead of doing it during the conversation start.

Model unload event is needed because that's the place to disable the `isOverriding` flags during the clothes editor. It might come in handy during some other future bugfixes as well since it's a quite distinct event in the model's lifecycle. I need it because there's a bug when you switch outfits: the game resets the hip bones(the ones that affect skirt physics) sliders and the tan color. For now it's fixed by keeping `isOverriding=true` while we're in editor. Unfortunately I'm unable to disable it when we leave the clothes screen so it stays enabled when we go to class and lowpolys load the extra hairs of the last character I clothed. I've no opportunity to perform that check you mention until a conversation starts but by then the damage is done. I could do it in some general game tick, which is another useful event to have for game state tracking. Looking forward to the trigger system which, I assume, is related to [this old issue](https://github.com/aa2g/AA2Unlimited/issues/7)

By "throwaway email" I meant that I won't use it to communicate so an email you don't mind throwing out in the open, like this page is. You still should be able to receive an invitation on it so it's not about the syntax but your own privacy. If that email is functional I'll send the invite there. If you prefer not to go into the den of autists, which aa2g steam group definitely is, then you may find the task tracker useful because that's where we'll be collecting our finds about stuff that is broken and who decided to work on it. So, for example, if you're going on an event hunt you might check the tracker first for wanted events and don't pass them. You can also ask us about the game mechanic because we've been playing it since almost the release. Just make a task for yourself, mentioning stuff you don't know about the game and we'll fill the blanks. I bet most of the concrete replies you got in the thread concerning the implementation was from the AAU team and maybe cuck anyway.

The poser has been @geneishouko's one-man show pretty much all this time. I'm doing mostly the releases, managing code, minor bugfixes and help out with tech-support in the thread. Your advice is still necessary, at least for me, because you're more familiar with the code and know more about the hacking part so you can stop me when I try to invent a square-wheeled bicycle.

**Comment by AA2Hackanon** [comment]
> The idea would be to add another case in ArchiveFileOpen.cpp, right? The only downside is if someone adds a room with a name breaking the pattern it falls apart.

That's indeed how one would do that. I assume the room files have to be listed in some sort of list file like they do it with the hairs; if that is the case, once could parse this file at some point and identify the room names this way. Adding a command to open a file from an archive should be rather easy, even without implementing it in aau itself, by just calling the function that illusion allready wrote for this.

> I need it because there's a bug when you switch outfits: the game resets the hip bones(the ones that affect skirt physics) sliders and the tan color.

I noticed something like this was happening and always procrastinated on finding out why the hell that happens. I'll look into an unload hi poly event, sounds like a good solution to it.

> Looking forward to the trigger system which, I assume, is related to this old issue

you're right, thats the issue i was thinking about. i'Ve got a [https://github.com/aa2g/AA2Unlimited/tree/aau_data_sets](branch) here if you want to look at it in its current state. UI is still a little bit sloppy and there are only a few basic events and actions, but the basic stuff is there.

> By "throwaway email" I meant that I won't use it to communicate so an email you don't mind throwing out in the open, like this page is. You still should be able to receive an invitation on it so it's not about the syntax but your own privacy. If that email is functional I'll send the invite there.

sounds perfect

> The poser has been @geneishouko's one-man show pretty much all this time. I'm doing mostly the releases, managing code, minor bugfixes and help out with tech-support in the thread. Your advice is still necessary, at least for me, because you're more familiar with the code and know more about the hacking part so you can stop me when I try to invent a square-wheeled bicycle.

lets see how the issue tracker thing works for that. you seem to be in contact with geneishouko, so most questions can probably be answered by him as well.

**Comment by linkanon** [comment]
Trying out the [sprintground ](https://aa2g.sprintground.com)instead of [teacmclerk ](https://teamclerk.com)for the task tracker. I've migrated all the current tasks and sent the invites so @AA2Hackanon  and @geneishouko should check your emails.
It looks better and has more features like comments on tasks, planning for releases, etc.
Also afaik we can open it to the public so that they can share the bugs they find but realistically no one will bother.

**Comment by AA2Hackanon** [comment]
@linkanon there is an event in the hair meshes called XXCleanup that is triggered when the xx files of a card are unloaded. its currently only used in the multiple hair functionality (so that the event does that and only that right now) so it might need some cleaning up before using it, but it looks like i wont really find a better hi poly cleanup event than that

**Comment by linkanon** [comment]
that's perfect, I think. I'll try it out.

**Comment by linkanon** [comment]
@AA2Hackanon [XXCleanupEvent](https://github.com/linkanon/AA2Unlimited/blob/bugfixes4/AAUnlimited/MemMods/Shared/Events/HairMeshes.cpp#L101) turned out to be triggered on both XX loading and XX unloading. Still useful because it's called consistently when a model unloads, I just had to add another flag to [GameState](https://github.com/linkanon/AA2Unlimited/blob/bugfixes4/AAUnlimited/Functions/AAPlay/GameState.cpp#L26) indicating whether there's a high poly model currently loaded on screen. I feel like it's a dirty solution but I'm keeping it for now because it works and there might be other uses for this flag in the future.

On an organizational note: 

1. I think test10 is pretty much ready for release. 
1. When starting to work on a feature or smth please make a task for it in the sprintground. Would be useful for compiling changelogs and plan what has to be done for release. Also give a clear feature outline of what's going on. Tasks are for developers and not for users so even tasks such as [Find more game data](https://aa2g.sprintground.com/view.php?id=10) are fine too.
1. Once we get used to sprintground I'll close all the stale issues. Maybe make a new one for communications like this. Let's use them either as a forum or as user reports.
