### ISSUE TITLE
PPX resource loader won't stay toggled off - using AA2MiniPPX for testing the Jizou crash I reported earlier.

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#316]
I am well aware the PPX resource loader in 1.6 does not work and crashes the game on attempting to launch, so I normally toggle it off. That toggle works on 1.5.3 and in AA2Mini normal version, but in AA2MiniPPX, it turns back on when the game shuts down. This is an AAU issue, but may or may not be on the AA2MiniPPX side of it. In other words, it is definitely an issue in AAU, but it may be caused by MiniPPX specifically since both my normal Mini and my installed AAU toggle off and stay off.

**Comment by k4yf0ur** [comment]
We [went over this](https://github.com/aa2g/AA2Unlimited/issues/290#issuecomment-812683708) alex. If you are using AA2MiniPPX you can't turn the toggle off because that's what loads the game files. 
The jizou crash isn't just a jizou crash, once the game is unstable enough clicking on any UI element will reproduce it. Opening the roster, or opening the config (settings) menu will also crash. Sometimes, you might see that the cards are missing from your class and the roster will have a gray tint. If that happens, that means AAU prevented a crash from happening and you should wrap your day up and save, since the game is unstable and close to crashing.

**Comment by alex20114349** [comment]
I didn't see that since I haven't been on for a while, but I just responded to it. Turning off PPX loader seems to work just fine, it loads the game and there are no crashes under the MiniPPX version of the game. It is only when PPX loader is on that I have had issues and it sounds like MiniPPX is specifically designed to keep PPX loader active, which pretty much solves the issue here since it is intended in that case.
