### ISSUE TITLE
Please enable Use .ppx resource loader by default for Windows?

### ISSUE THREAD

**Issue by dani02021** [aa2g/AA2Unlimited#345]
The game crashes every time when going to H scene. throws invalid access error. It seems that the error is caused if this option is disabled. I am using the default modules and scripts.

It can prevent these crashes for newcommers like me.

Using newest version of AA2Unlimited

**Comment by k4yf0ur** [comment]
The [PPeX](https://github.com/aa2g/AA2Unlimited/wiki/PPeX) functionality implements a new file type called ppx that the game still reads, but that takes up significantly less storage space than the vanilla .pp files, and is believed to be more stable than the pp2 alternative. You are only supposed to use it along with ppx mods. We won't set this to be the default on windows 10 because this option isn't supposed to be turned on for users that installed aa2 the old way. For users of [PPX Mini](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub), the option is enabled by default.
