### ISSUE TITLE
How come?

### ISSUE THREAD

**Issue by xayneg** [aa2g/AA2Unlimited#391]
I don't know if it's OK to post this but anyway...

How come does that my char loses in battle to some other chars that don't even have any Martial Artist/Armed/Tactics modules?? Or not even a single module whereas mine has these...

Dunno if having Undead module has something to do with...

**Comment by linkanon** [comment]
some factors:

You're significantly weaker
If you have a specific race then they could have a `Natural Enemy` against that race

`Martial Artist` doesn't guarantee a win, it simply guarantees the stance advantage, which can still be overcome by strength
`Armed` only affects stabbings
`Battle Tactics` affects the battle outcome
`Martial Arts Prodigy` can affect a fight outcome so check if they have that

**Comment by xayneg** [comment]
That's my issue, I got that Martial Artist doesn't give you a 100% Win ratio (the module description is pretty clear) but even if having STR 999/9 and One Blow I still somehow lose (to 0 modules chars even). And I've come to think that also having 'Undead' (doesn't/can't die) module resets my stats (?) thus losing to "stronger" ones.

Thanks for the reply tho.

**Comment by linkanon** [comment]
`Race-Undead` doesn't really affect anything, it only marks you as `Undead` so that other racist modules can act on it
If you meant `Undying` then that is a different thing. It doesn't make you win a fight, nor does it protect you from a murder. It's just if the character got murdered they get resurrected the next day(they'll be down for the full day and resurrect when you get home normally). If you're the Undying PC that is getting stabbed then you go to the straight game over. It's mostly useless on PCs. If you want more chances to survive then get the `Armed` module and the Lucky trait
