### ISSUE TITLE
High Pixel Density Skin: Black Face

### ISSUE THREAD

**Issue by imjustaskin** [aa2g/AA2Unlimited#40]
**AA2 Make:**
![image](https://cloud.githubusercontent.com/assets/27628835/25071835/3c9eeae0-22c1-11e7-8e9d-6503f4d81316.png)

**AA2 Install (Mods Installed):**
![image](https://cloud.githubusercontent.com/assets/27628835/25071826/3368de40-22c1-11e7-833a-1713d2d88571.png)

**Comment by linkanon** [comment]
is this an illustration of the mod not working or of what problem it's supposed to solve?

**Comment by imjustaskin** [comment]
exactly.

using:
- AA2Face
- AA2Unlimited
- AA2Snowflake
- ReiEditAA2

Pretty sure the mods installed shouldnt interfere with the skin, with AA2Face & AA2Unlimited not activated, the face is still black.

However, when changing the face with AA2Face in the AA2 Maker, the face returns normal.. So it could be the HEXA more faces mod not working correctly with the skin.

**Comment by linkanon** [comment]
How did you install the mod? It could be an AA2Install issue since I can't reproduce it on my end. Try force installing it or installing it manually(merge the files in the mod where they belong. Also check which ones didn't install if that's the case)

**Comment by imjustaskin** [comment]
![image](https://cloud.githubusercontent.com/assets/27628835/25091033/1e9fb472-2387-11e7-9cf3-d759378a52f9.png)

No conflicts, everything injected. 

There's also another skin called "[AA2][Skin][HI_RES_SKIN+LIPS+CUM][Alexae]", which works. however, with that one it changes the saturation of every skin.

**Comment by linkanon** [comment]
I wouldn't trust the log. Open the files in question in SB3U and see that the new files are all in place.
Here's an explanation of the issue for some insight:
- there's a bunch of skin textures in `jg2e03_00_00.pp`
- their resolutions are mentioned in` jg2e00_00_00.pp`/`jg2p_00_01_00_02.lst`
- the game uses these textures to apply the skin shadows and highlights
- the game uses these resolutions to compute how the tan should look
- high pixel density means the skin is more high res so the game doesn't try to blur the tan as much and it looks crisp
- so what the mod does is it's replacing the skin textures with high-res versions that still look the same and adjusting the resolution in the `.lst` file
- if you get black whatever it means you probably didn't install the .lst so make sure the .lst you have and the one in the mod are the same.

I get reports it doesn't work from time to time but can't reproduce it so if you dont' want to deal with it just use tantoo to install this skin since this is what I'm attempting to make AA2Install-ready

**Comment by imjustaskin** [comment]
Fixed it. I wasnt aware that there was a program like SB3U, thanks for the help.

1. I installed the mod with AA2Install
2. Used SB3U to check the files, indeed, the files werent applied
3. Applied them all, problem still persists

**Comment by Saint3d** [comment]
eso sucede por que no existe el archivo especifico del bronceado del personaje, para solucionarlo simplemente usa otro bronceado con el editor del unlimited, no deberia haber ningun problema por que a mi me sirvio cualquiera, abajo esta un ejemplo
This happens because there is no specific file for the character's tan, to solve it simply use another tan with the unlimited editor, there shouldn't be any problem because any one worked for me, here's an example:
![image](https://user-images.githubusercontent.com/108374860/193723110-373cb0c1-262e-4b9c-b254-4f38a18bdf61.png)


![image](https://user-images.githubusercontent.com/108374860/193722283-ad12c721-978b-4be1-9228-2f8f70818cfc.png)
