### ISSUE TITLE
The issue continues...

### ISSUE THREAD

**Issue by KuroHazama** [aa2g/AA2Unlimited#44]
I have everything in the folder even the DLL and yet the same LoadLibrary error appears. I can't see anything else I can do. :I I tried looking up a video but nothing. I'm just not understanding what went wrong since everything is in place. I downloaded the latest release, did the steps and didn't work. I used the master unlimited and still didn't work.

I put everything from the Unlimited folder into the play folder and still nothing. Also it doesn't detect a modded play I have. It's a modded play someone made for yaoi scense to be enabled.  It detects the edit EXE though.

**Comment by linkanon** [comment]
Hi, "I did everything right but nothing works" is almost never the case. So it's probably "I *think* I did everything right but nothing works". I suggest you make lots of screenshots of your AA2Play and AA2Edit folders, where you put AAUnlimited and how you're launching it so that it's easier for me to spot what you could've done wrong.

**Comment by KuroHazama** [comment]
I found the issue. For some reason when I run my game as an admin, it will not find my game. Sorry.
