### ISSUE TITLE
Can't save on Linux

### ISSUE THREAD

**Issue by amenokagaseo** [aa2g/AA2Unlimited#470]
Title. Attempting to save the game simply results in nothing happening, as if the class folder under data simply wasn't there. I've attempted multiple permissions edits to the folder, as well as emptying it, and nothing works.

**Comment by amenokagaseo** [comment]
Closing this, not an AAUnlimited issue but a WINE bug that I discovered after further investigation. The game seems to not recognize files outside its own locale, characterset, or runtime permissions unless run with wine-ge or staging.

**Comment by VeggieTime** [comment]
I've solved this issue by using Proton. I followed the installation steps on wine and had the same problem not being able to save, and I was already losing my head because I'm not really tech savy on Linux or Wine. I don't really looked into staging, I don't know what it is and I didn't really feel like installing wine-ge. So I tried one last time following the steps but with Proton, by "Adding a non-Steam game", and then on Properties changing the executable to install the dependencies (thanks to Gaming on Linux on YT for that one). After that you go to properties again and in Launch Options tell it to use japanese like you do with Wine. I also add I line for sound, I don't know if it does something but it fixes noise on several other games. Tested on Linux Mint 22.1 Xia with Proton 9.0-4 and I can finally save.

I'm not sure how posting in here works, so sorry if I'm breaking any rules by doing it on a solved issue but I don't know if I should create one since I don't have a problem. I thought I let others know in case they have the same problem, I haven't seen anything about it here or in the Discord server.
